[SERVICE]
    Flush        1
    Parsers_File parsers.conf

[INPUT]
    Name         tail
    Path         /var/log/flaskapp/app.log
    Tag          flask.app
    Parser       json

[FILTER]
    Name         rewrite_tag
    Match        flask.app
    Rule         $levelname ^(WARNING|ERROR|CRITICAL)$  flask.alert  true

[OUTPUT]
    Name         loki
    Match        flask.*
    Host         127.0.0.1  # <-- Need to update, Server 2 IP
    Port         3100
    Labels       job=flask_app

[OUTPUT]
    Name         cloudwatch_logs
    Match        flask.alert
    region       ap-southeast-1
    log_group_name flask-critical-alerts
    log_stream_name app-instance-01
    auto_create_group On