version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: local-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: local-grafana
    ports:
      - "3000:3000"
    restart: unless-stopped